echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
echo "[Desktop Entry]">"power meter.desktop"
echo "Version=1.0">>"power meter.desktop"
echo "Name=Power meter">>"power meter.desktop"
echo "Comment=Optical power meter with USB camera">>"power meter.desktop"
echo "Type=Application">>"power meter.desktop"
echo "Exec=\""$PWD"/power-meter64\"">>"power meter.desktop"
echo "Icon="$PWD"/resources/icon/icon.png">>"power meter.desktop"
echo "Terminal=false">>"power meter.desktop"
chmod u+x "power meter.desktop"
